### ISSUE TITLE
Integrate mailing list with homepage

### ISSUE THREAD

**Issue by sdosemagen** [jywarren/plots#127]
Point: Sara
Team: RJ, Stewart, Shannon, Jeff
Importance: Medium- October suggested
- How to integrate mailing list with homepage - takes up big bandwidth on the homepage - clearer ways that the mailing list and website interface - feeds that mention a place or tool are added into online “archive” of pages

**Comment by swylie** [comment]
Draft Overview of Issue Goals: The goal of this project is to increase interaction between the mailing list and the website by facilitating the push and pull of data and conversations between these two communication methods. Specifically we will review and revise current cross communication such as the mailing list feed on the website.

**Comment by rjcorwin** [comment]
> feeds that mention a place or tool are added into online “archive” of pages

Hmmm. Not sure we could automate this but it might not be that crazy to make it a manual process. Perhaps a UI for blazing through the activity and adding tool/place tags to posts.  Bonus points for figuring out a way to crowd source this activity to the community...

**Comment by ebarry** [comment]
could we consider potential twitter integration as part of this issue? some websites show a running tally of tweets on their homepage. I am personally ambivalent about this but think it is a good thing to think about.

**Comment by jywarren** [comment]
Twitter integration should be it's own issue, wouldn't be hard to do... please file! 

This issue is a duplicate with both:

https://github.com/jywarren/plots/issues/116

https://github.com/jywarren/plots/issues/12

Copying to #12 and closing. If the specific issue of the display of the mailing list on the front page is it's _own_ issue, feel free to reopen and make this one more specific.
