### ISSUE TITLE
ability to comment inline in a map -- "annotations"

### ISSUE THREAD

**Issue by jywarren** [jywarren/plots#26]

**Comment by rjcorwin** [comment]
Woot! I set up the basic Drupal infrastructure for this in a VirtualBox sandbox weekend before last.  This coming weekend I'll build the UI for making it user friendly.  I'm going start by taking Jeff's lead on this and make this a custom job by handcoding the JS.  The more "Drupal" way would be to build a Layers plugin for the openlayers module that uses the current node to gather the settings needed...but I have a suspicion that the OL module will need to be modified some way to support "multiple layers all at once" as Jeff is currently doing in the js in node-map.tpl.php.  So before I embark on trying to coherently modify the Open Layers module, I think it's best if I understand a little more about how it needs to be done using the OpenLayers.js library in the first place.  

If anyone has OpenLayers.js chops and wants to join me at the Pirate Ship or on chat, we could probably crank this out in a couple hours.

**Comment by ebarry** [comment]
cool! do you have a sketch of what you think the UI will look like that you can post?

**Comment by rjcorwin** [comment]
No sketch yet.  Going for the basics.  Annotations will be markers with popups.  To add an annotation there will be a "Add annotation" link that will pop the map up to full screen with the Map Annotation form in a right column.  Further work could be done to make viewing annotations more accessible.  Something like an addition to fullscreen mode where you have annotations in a right column that you can scroll through, click on one, and then have it focused on the map.

**Comment by ebarry** [comment]
that sounds really great!!! talking maps. thank you for making this cool!

On Fri, Nov 18, 2011 at 12:48 PM, R.J. Steinert (rjstatic) <
reply@reply.github.com

**Comment by rjcorwin** [comment]
Trying to do this "the easy way" by having drupal add a few things and writing some JS to strap it all together has proved difficult because the amount  of JS on the page.  I keep running into strange behaviors and I think it's due to the amount of unrelated cruft that exists.  I've ran into this before where it's best to just write something that lives on it's own iframe pointed to a simple HTML file with some JS and makes web services calls to Drupal.  Using the Services module we'll do Create, Update, and Delete for Annotation nodes (example: http://drupal.org/node/1354202) and using Views Datasource module (http://drupal.org/project/views_datasource) we'll create a JSON service (I have created in my Sandbox) for Read operations.  To be continued.

**Comment by jywarren** [comment]
If you do it in a separate view that sounds fine -- then doing embeddable maps is easy too.

**Comment by jywarren** [comment]
it sounds like you are being a badass, rj. let's coordinate also because i'm trying to add the "related maps" feature and adding arbitrary layers in overlaps a bit with moving to an iframe. Maybe we can pass a list of map ids in via an argument in the iframe src param.

**Comment by rjcorwin** [comment]
Ah, this ticket? https://github.com/jywarren/plots/issues/28

Sounds interesting.  I should be at the ship tomorrow morning, not sure about the afternoon though.  And ya, +1 for embedable.  It will also make the fullscreen mode way easier to manage.

**Comment by jywarren** [comment]
Duplicate with newer https://github.com/jywarren/plots/issues/131, closing and merging with newer conversation.
