### ISSUE TITLE
"Read more" links in Notification emails are butchered

### ISSUE THREAD

**Issue by rjcorwin** [jywarren/plots#65]
I think the issue is that Notifications thinks it's sending an HTML email out but tags are being stripped so the "http://ShortenedURL.com/somethingReallyCoo..." that should point to "http://ShortenedURL.com/somethingReallyCool" ends up pointing to "http://ShortenedURL.com/somethingReallyCoo"

Example:

On Sun, Jan 29, 2012 at 10:55 PM, site@publiclaboratory.org wrote:

> Greetings rjstatic,
> 
> mathew wrote:
> 
> Instead of using a balled up piece of tape, a pebble, or some other thing to
> hold down my camera's shutter, I've gone to using a knot.  This makes it easy to
> hold in place, and makes setting it easier.  I prefer a rubber band, but tape
> also holds it down.  tape may be more useful for bulging, non rectangular
> cameras.
> 
> My Canon SD1000 needs the rubber band tripled up to hold it in place:
> 
> Read more
> http://publiclaboratory.org/notes/mathew/1-29-2012/using-knot-trigger-ca...
> [1]

**Comment by rjcorwin** [comment]
While we're at it, the Sender currently says "Site".  Could be something more useful like the username of the person who triggered the notification.

**Comment by jywarren** [comment]
Yeah i saw that, it's frustrating. I think it's a collision of the input
filters and the mailer... i bet there's others out there who've dealt with
this.

On Mon, Jan 30, 2012 at 5:14 AM, R.J. Steinert <
reply@reply.github.com

> wrote:
> 
> I think the issue is that Notifications thinks it's sending an HTML email
> out but tags are being stripped so the "
> http://ShortenedURL.com/somethingReallyCoo..." that should point to "
> http://ShortenedURL.com/somethingReallyCool" ends up pointing to "
> http://ShortenedURL.com/somethingReallyCoo"
> 
> Example:
>

**Comment by jywarren** [comment]
http://drupal.org/node/218968 offers a solution, trying...

**Comment by jywarren** [comment]
That wasn't quite it, it was for the "subscriptions" module and we use "notifications", but I think it may relate to the option "use printer-friendly URLs" on this page: http://publiclaboratory.org/admin/content/node-type/note

I'm attempting to uncheck that for print-formatting, since it's under the heading "Printer, e-mail and PDF versions". Maybe this will allow the urls to display fully.

**Comment by jywarren** [comment]
That didn't work - nor did turning it off for PDF versions, or globally here: http://publiclaboratory.org/admin/settings/print

I wonder if you have to flush caches or something...

ok i figured it out -- i went to "messaging settings" in the "messaging & notifications" menu and under "Message body filter
" i chose "messaging plain text" instead of "html and markdown". done!

**Comment by rjcorwin** [comment]
Nice!

On Sun, Feb 12, 2012 at 11:45 AM, Jeffrey Warren
reply@reply.github.com
wrote:
